config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'home#index'

  resources :domains, only: [:new, :create, :edit, :update, :destroy, :show] do
    collection do
      get :add_domains
      post :save_domains
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/domain.rb
class Domain < ActiveRecord::Base
  belongs_to :user
  has_many :domain_ranks

  before_validation :limits_check, on: :create
  def limits_check
    if !(self.user.domains.count < GeneralConfig.domain_limit)
      errors.add(:url, "allowed url limits reached")
      false
    else
      self.user.domains.count < GeneralConfig.domain_limit
    end
  end
end

app/models/domain_rank.rb
class DomainRank < ActiveRecord::Base
  belongs_to :domain
end

app/models/general_config.rb
class GeneralConfig < ActiveRecord::Base
  def self.basics_config
    if self.first
      self.first.cron_time
    else
      "12pm"
    end
  end

  def self.domain_limit
    if self.first
      self.first.domain_limit
    else
      3
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :domains

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_domain, only: [:edit, :update, :destroy, :show]

  def add_domains
  end

  def save_domains
  	if params[:domain_1].present?
      domain_1 = sep_domain(params[:domain_1])
      if domain_1.present?
        current_user.domains.first.update(url: domain_1) if current_user.domains.first.present?
        current_user.domains.create(url: domain_1) if current_user.domains.empty?
      end
    end
  end

  def new
    @domain = current_user.domains.new
  end

  def create
    @domain = current_user.domains.new(domain_params)
    @domain.url = sep_domain(params[:domain][:url])
    respond_to do |format|
      if @domain.url.present? && @domain.save
        format.html { redirect_to root_url, notice: 'Domain was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    gen_chart
  end

  def edit
  end

  def update
    respond_to do |format|
      if domain_check_and_update
        format.html { redirect_to root_url, notice: 'Domain was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Domain was successfully destroyed.' }
    end
  end

  private
  def domain_check_and_update
    domain_url = sep_domain(params[:domain][:url])
    if domain_url.present?
      @domain.update(domain_params)
      @domain.update(url: domain_url)
    else
      false
    end
  end

  def sep_domain(domain_url)
    url = Domainatrix.parse(domain_url)
    if url.domain.present?
      url.domain+"."+url.public_suffix
    else
      url.domain
    end
  end

  def set_domain
    @domain = Domain.find(params[:id])
  end

  def domain_params
    params.require(:domain).permit(:url, :name, :description)
  end

  def gen_chart
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.title(text: "#{@domain.url} day vs rank ")
      f.xAxis(categories: @domain.domain_ranks.collect{|dr| dr.rank_time.strftime("%A")})
      f.series(name: "Rank in Billions", yAxis: 0, data: @domain.domain_ranks.collect(&:rank))

      f.yAxis [
        {title: {text: "Rank in Billions", margin: 70} },
      ]

      f.legend(align: 'right', verticalAlign: 'top', y: 75, x: -50, layout: 'vertical')
      f.chart({defaultSeriesType: "column"})
    end

    @chart_globals = LazyHighCharts::HighChartGlobals.new do |f|
      f.global(useUTC: false)
      f.chart(
        backgroundColor: {
          linearGradient: [0, 0, 500, 500],
          stops: [
            [0, "rgb(255, 255, 255)"],
            [1, "rgb(240, 240, 255)"]
          ]
        },
        borderWidth: 2,
        plotBackgroundColor: "rgba(255, 255, 255, .9)",
        plotShadow: true,
        plotBorderWidth: 1
      )
      f.lang(thousandsSep: ",")
      f.colors(["#90ed7d", "#f7a35c", "#8085e9", "#f15c80", "#e4d354"])
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # Using it just as home page.
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/general_configs/index.html.erb
<%= form_for @config, url: admin_general_configs_path,:method => :POST, html: {class: 'form-horizontal'} do |f| %>
  <pre>
  <p>
  Cron Time: <%= f.number_field :cron_time, placeholder: 'Cron Time', required: true, in: 0..23 %>
  
  Domain Limit: <%= f.number_field :domain_limit, placeholder: 'Domain Limit', required: true, max: 999 %>
  </p>
  <button type="submit" class="btn btn-blue">Submit</button>
  </pre>
  <div><%= link_to 'Dashboard', admin_dashboard_path %></div>
<% end %>

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url, "Domain Url" %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/domains/add_domains.html.erb
<p> page for adding domains </p>
<%= form_tag save_domains_domains_path, method: :post do %>
  <%= label_tag :domain_1, "Domain 1:" %>
  <%= text_field_tag :domain_1 %></br>
  <%= label_tag :domain_2, "Domain 2:" %>
  <%= text_field_tag :domain_2 %></br>
  <%= label_tag :domain_3, "Domain 3:" %>
  <%= text_field_tag :domain_3 %></br>
  <%= submit_tag "Add Domains" %></br>
<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

app/views/domains/show.html.erb
<%= high_chart_globals(@chart_globals) %>
<%= high_chart("some_id", @chart) %>

app/views/home/index.html.erb
<p> Home Page </p>
<!-- link adding for user login/logout -->
<% if current_user.present? %>
  <%= link_to "sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %><br />
<% end %>
<br />
<% if current_user.domains.count < GeneralConfig.domain_limit %>
  <%= link_to "Add Domain", new_domain_path %>
<% end %>

<table>
	<tr>
  	<th> Url </th>
  	<th> Domain Rank </th>
  	<th> High Chart </th>
  	<th> Edit </th>
  	<th> Destroy </th>
	</tr>
<% current_user.domains.each do |domain| %>
  <tr>
  <td><%= domain.url %></td>
  <td><%= domain.domain_ranks.last.present? ? domain.domain_ranks.last.rank : nil %></td>
  <td><%= link_to 'Show', domain %></td>
  <td><%= link_to 'Edit', edit_domain_path(domain) %></td>
  <td><%= link_to 'Destroy', domain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RankingDisplay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>